### ISSUE TITLE
Modify rjm_texbleed to support rgba where every channel is a float?

### ISSUE THREAD

**Issue by fire** [rmitton/rjm#3]
Is it possible to modify rjm_texbleed to support floating point rgba?

**Comment by rmitton** [comment]
Wasn't planning on doing it, but it should be a pretty easy modification for someone to hack together themselves.

**Comment by fire** [comment]
Thanks. If I get time, I might make a pull request.

**Comment by fire** [comment]
How would you deal with a number that is in decimal format versus like a number from 0 to 255 with floats?

**Comment by rmitton** [comment]
I think you'd only need to make a couple of changes --
- `BLEED_THRESHOLD` should probably be 0.5 instead of 128, or maybe user configurable.
- The final comparison of `(dst[ac] == 0)` might want to use a small epsilon value (e.g. 0.0001) instead of checking against exactly zero. It would depend on what you were using it for I suppose.

**Comment by fire** [comment]
Can you review this?

Does the library deal with the SRGB range being 0 and 1 or 0 to 255? 

Trying to handle the cases

1. when the SRGB number goes 0 to 1 and goes above 1 
1. 0 to 255 and goes above that.
